@extends('layouts.frontend')
@section('title','Order '.$order->order_number)
@section('content')
@inject('orderStatusService', 'App\Domains\Order\Services\OrderStatusService')
<section class="py-5"><div class="container">
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">{{ $order->order_number }}</h1><div class="text-muted">{{ $order->placed_at?->format('d M Y') }}</div></div><div class="d-flex gap-2"><a href="{{ route('customer.orders.invoice', $order->order_number) }}" class="btn btn-outline-success" target="_blank">View/Print Invoice</a><a href="{{ route('customer.orders.index') }}" class="btn btn-outline-secondary">Back</a></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white fw-semibold">Order Timeline</div><div class="card-body"><div class="d-flex flex-wrap gap-2">@foreach($statusTimeline['steps'] as $step)@php $badgeClass = match ($step['state']) { 'completed' => 'text-bg-success', 'current' => 'text-bg-warning', default => 'text-bg-light border' }; @endphp<span class="badge {{ $badgeClass }} px-3 py-2">{{ $step['label'] }}</span>@endforeach @if($statusTimeline['final_state'])<span class="badge text-bg-danger px-3 py-2">{{ $statusTimeline['final_state'] }}</span>@endif</div></div></div>
<div class="card border-0 shadow-sm"><div class="card-body"><div class="d-flex flex-wrap gap-2 mb-3"><span class="badge text-bg-light border">{{ $orderStatusService->label($order->order_status) }}</span><span class="badge text-bg-light border">{{ strtoupper($order->payment_method) }} / {{ str($order->payment_status)->headline() }}</span></div>@foreach($order->items as $item)<div class="border-bottom pb-2 mb-2"><div class="fw-semibold">{{ $item->product_name_snapshot }}</div><div class="small text-muted">{{ $item->variant_name_snapshot }} x {{ rtrim(rtrim(number_format((float)$item->quantity,3),'0'),'.') }} - Rs. {{ number_format((float)$item->line_total,2) }}</div></div>@endforeach<hr>@if($order->discount_total > 0)<div class="d-flex justify-content-between text-success"><span>Coupon Discount</span><span>- Rs. {{ number_format((float)$order->discount_total,2) }}</span></div>@endif<div class="h5 mt-2">Grand Total: Rs. {{ number_format((float)$order->grand_total,2) }}</div></div></div></div></section>
@endsection
