@extends('layouts.frontend')
@section('title','My Account')
@section('content')
<section class="py-5"><div class="container">
<div class="d-flex flex-wrap justify-content-between gap-3 mb-4"><div><h1 class="h3 mb-1">My Account</h1><div class="text-muted">{{ $customer->mobile }}</div></div><form method="POST" action="{{ route('customer.logout') }}">@csrf<button class="btn btn-outline-secondary">Logout</button></form></div>
<div class="row g-4">
<div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="fw-semibold">{{ $customer->name }}</div>@if($customer->is_premium)<span class="badge text-bg-success mt-2">Premium</span>@endif<div class="text-muted small mt-2">{{ $customer->email ?: 'No email added' }}</div><a href="{{ route('customer.cashback.index') }}" class="btn btn-sm btn-outline-success mt-3">Cashback</a></div></div></div>
<div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body"><div class="d-flex align-items-start justify-content-between gap-3"><div><div class="text-muted small">Saved addresses</div><div class="h4 mb-3">{{ $customer->addresses_count }}</div><a href="{{ route('customer.addresses.index') }}" class="btn btn-sm btn-outline-success">Manage Addresses</a></div><span class="d-inline-flex align-items-center justify-content-center rounded-circle bg-success-subtle text-success flex-shrink-0" style="width: 42px; height: 42px;"><i class="fa-solid fa-location-dot" aria-hidden="true"></i></span></div></div></div></div>
<div class="col-md-4"><div class="card border-0 shadow-sm h-100"><div class="card-body d-grid gap-2"><a href="{{ route('cart.show') }}" class="btn btn-success">View Cart</a><a href="{{ route('customer.orders.index') }}" class="btn btn-outline-secondary">Order History</a><a href="{{ route('customer.returns.index') }}" class="btn btn-outline-secondary">Returns</a><a href="{{ route('customer.notifications.index') }}" class="btn btn-outline-secondary">Notifications</a></div></div></div>
</div>
<div class="card border-0 shadow-sm mt-4"><div class="card-header bg-white fw-semibold">Latest Orders</div><div class="card-body">@forelse($orders as $order)<div class="d-flex flex-wrap justify-content-between border-bottom pb-2 mb-2"><a href="{{ route('customer.orders.show', $order->order_number) }}">{{ $order->order_number }}</a><span>{{ str($order->order_status)->headline() }}</span><strong>Rs. {{ number_format((float)$order->grand_total,2) }}</strong></div>@empty<x-empty-state title="No orders yet" message="Your recent orders will appear here after checkout." :action="route('products.index')" action-label="Browse products" />@endforelse</div></div>
</div></section>
@endsection
