@extends('layouts.admin')
@section('title','Delivery Slots')
@section('admin-content')
<div class="d-flex justify-content-between align-items-center mb-4"><div><h1 class="h3 mb-1">Delivery Slots</h1><div class="text-muted">Manage checkout delivery windows.</div></div><a href="{{ route('admin.delivery-slots.create') }}" class="btn btn-success">Add Slot</a></div>
@if (session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if ($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="card border-0 shadow-sm mb-4"><div class="card-body"><form method="GET" class="row g-3"><div class="col-md-5"><input name="search" value="{{ request('search') }}" class="form-control" placeholder="Search slots"></div><div class="col-md-3"><select name="status" class="form-select"><option value="">All</option><option value="1" @selected(request('status')==='1')>Active</option><option value="0" @selected(request('status')==='0')>Inactive</option></select></div><div class="col-md-2"><button class="btn btn-outline-success w-100">Filter</button></div></form></div></div>
<div class="card border-0 shadow-sm"><div class="table-responsive"><table class="table mb-0 align-middle"><thead class="table-light"><tr><th>Name</th><th>Time</th><th>Label</th><th>Status</th><th>Order</th><th class="text-end">Actions</th></tr></thead><tbody>@forelse($slots as $slot)<tr @class(['table-warning'=>$slot->trashed()])><td class="fw-semibold">{{ $slot->name }}</td><td>{{ substr($slot->start_time,0,5) }} - {{ substr($slot->end_time,0,5) }}</td><td>{{ $slot->display_label ?: $slot->name }}</td><td><span class="badge {{ $slot->status ? 'text-bg-success':'text-bg-secondary' }}">{{ $slot->status ? 'Active':'Inactive' }}</span></td><td>{{ $slot->display_order }}</td><td class="text-end">@if(!$slot->trashed())<a href="{{ route('admin.delivery-slots.edit',$slot) }}" class="btn btn-sm btn-outline-success">Edit</a><form method="POST" action="{{ route('admin.delivery-slots.destroy',$slot) }}" class="d-inline">@csrf @method('DELETE')<button class="btn btn-sm btn-outline-danger">Delete</button></form>@else<form method="POST" action="{{ route('admin.delivery-slots.restore',$slot->id) }}" class="d-inline">@csrf @method('PATCH')<button class="btn btn-sm btn-outline-success">Restore</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-center text-muted py-5">No slots found.</td></tr>@endforelse</tbody></table></div><div class="card-footer bg-white">{{ $slots->links() }}</div></div>
@endsection
