@extends('layouts.frontend')

@section('title','My Cashback')

@section('content')
<section class="py-5"><div class="container">
<div class="d-flex justify-content-between mb-4"><div><h1 class="h3 mb-1">My Cashback</h1><div class="text-muted">Cashback is processed after {{ $rule->processing_delay_days }} days from delivery.</div></div>@if($customer->is_premium)<span class="badge text-bg-success align-self-start">Premium</span>@endif</div>
@if(session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
@if($errors->any())<div class="alert alert-danger">{{ $errors->first() }}</div>@endif
<div class="row g-4 mb-4"><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-muted">Balance</div><div class="h4">Rs. {{ number_format($balance,2) }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-muted">Pending</div><div class="h4">Rs. {{ number_format($pendingAmount,2) }}</div></div></div></div><div class="col-md-4"><div class="card border-0 shadow-sm"><div class="card-body"><div class="text-muted">Redeemable</div><div class="h4">Rs. {{ number_format($availableAmount,2) }}</div></div></div></div></div>
<div class="card border-0 shadow-sm mb-4"><div class="card-header bg-white fw-semibold">Request Redemption</div><div class="card-body"><p class="text-muted">Redemption is available in multiples of Rs. {{ number_format((float)$rule->redemption_multiple,2) }}. Approved requests generate a coupon.</p><form method="POST" action="{{ route('customer.cashback.redeem') }}" class="row g-3">@csrf<div class="col-md-4"><input type="number" step="0.01" name="requested_amount" class="form-control" placeholder="Amount"></div><div class="col-md-6"><input name="customer_note" class="form-control" placeholder="Note optional"></div><div class="col-md-2"><button class="btn btn-success w-100" @disabled($availableAmount < (float)$rule->redemption_multiple)>Redeem</button></div></form></div></div>
<div class="row g-4"><div class="col-lg-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Ledger</div><div class="card-body">@forelse($ledgers as $ledger)<div class="border-bottom pb-2 mb-2">{{ $ledger->ledger_type }} Rs. {{ number_format((float)$ledger->amount,2) }} / Balance Rs. {{ number_format((float)$ledger->balance_after,2) }}</div>@empty<div class="text-muted">No cashback yet.</div>@endforelse</div></div></div><div class="col-lg-6"><div class="card border-0 shadow-sm"><div class="card-header bg-white fw-semibold">Cashback Coupons</div><div class="card-body">@forelse($coupons as $coupon)<div class="border-bottom pb-2 mb-2"><div class="fw-semibold">{{ $coupon->code }}</div><div class="small text-muted">Rs. {{ number_format((float)$coupon->discount_value,2) }}</div></div>@empty<div class="text-muted">No cashback coupons yet.</div>@endforelse</div></div></div></div>
</div></section>
@endsection
